package mobiledev.unb.ca.roompersistencelab.entity;

import androidx.room.Entity;

@Entity(tableName = "item_table")  // Represents a SQLite table
public class Item {
    // TODO Create the values for the entity
    //  You will need to add variables for the column names of id, name, and num
    //  NOTE: id is an autogenerated attribute
    // Additional details can be found at https://developer.android.com/reference/android/arch/persistence/room/Entity
}
